import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text

# ==========================================
# 1. IMPORT NECESSARY LIBRARIES
# ==========================================
# Import pandas, DecisionTreeClassifier, and export_text


# ==========================================
# 2. CREATE THE DUMMY DATASET USING PANDAS (X and y)
# ==========================================
# Create a DataFrame with age, salary, and purchase status (same as yesterday)[cite: 8]
df = pd.DataFrame({
    'Yas': [25, 35, 45, 20, 55, 60],
    'Maas': [40000, 60000, 80000, 20000, 120000, 100000],
    'Satin_Alma': [0, 0, 1, 0, 1, 1]
})

# Extract features (X) and target variable (y) from the DataFrame[cite: 8]
X = df[['Yas', 'Maas']].values
y = df['Satin_Alma'].values


# ==========================================
# 3. TRAIN THE DECISION TREE MODEL (.fit)
# ==========================================
# Note: Since trees look at rules rather than distances, we do not use StandardScaler[cite: 8]
model = DecisionTreeClassifier(random_state = 42)
model.fit(X, y)


# ==========================================
# 4. MAKE A NEW PREDICTION (.predict)
# ==========================================
# Ask the same customer we asked yesterday (40 years old and 70,000 salary) to this model[cite: 8]
print(model.predict([[40, 70000]]))


# ==========================================
# 5. EXTRA CHALLENGE (Viewing Decision Tree Rules)
# ==========================================
# Export and print the internal if-else rules generated by the model[cite: 8]
kurallar = export_text(model, feature_names=["Yas", "Maas"])
print(kurallar)